[tool.poetry]
name = "django-sample-project"
version = "0.1.0"
description = ""
authors = ["ktrw <ktr.w1011@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
